# Generated by Django 4.1.1 on 2022-09-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0002_room_host'),
        ('chatterbox', '0004_remove_room_host_remove_room_participants'),
    ]

    operations = [
    ]
